[options]
forward_x11 = true
docker_in_docker = true

[workspace]
user = "dev"
hostname = "ops"
default_shell = "zsh"
tools = [
    "ansible",
    "awscli2",
    "dig",
    "dive",
    "docker",
    "fluxctl",
    "git",
    "iproute2",
    "iputils",
    "kn",
    "krew",
    "kubecolor",
    "kubectl",
    "kubectx",
    "kubernetes-helm",
    "mysql-shell",
    "netcat",
    "openssh",
    "python310",
    "python310Packages.pip",
    "scaleway-cli",
    "terraform",
    "thefuck",
    "vault",
    "vim",
    "xclip",
]

[[workspace.volumes]]
host = "/tmp/kitt"
bind = "/tmp/host"
mode = "rw"

[[workspace.volumes]]
host = "$HOME"
bind = "/home/charles/host"
mode = "ro"

[[workspace.volumes]]
host = "$HOME/.ssh"
bind = "/home/charles/.ssh"
mode = "ro"

[[workspace.volumes]]
host = "$HOME/.kube"
bind = "/home/charles/.kube"
mode = "ro"

[[workspace.envs]]
name = "DOCKER_BUILDKIT"
value = "1"

[[workspace.envs]]
name = "TIMER_FORMAT"
value = "[%d]"

[[workspace.envs]]
name = "TIMER_PRECISION"
value = "2"

[[workspace.envs]]
name = "MAGIC_ENTER_GIT_COMMAND"
value = "git status"

[[workspace.envs]]
name = "MAGIC_ENTER_OTHER_COMMAND"
value = "ls"

[plugins]

    [plugins.zsh]
    theme = "afowler"
    plugins = [ 
        "aliases", 
        "ansible", 
        "aws", 
        "copybuffer", 
        "docker", 
        "git", 
        "helm", 
        "kn", 
        "kubectl", 
        "kubectx", 
        "magic-enter", 
        "pip", 
        "python", 
        "terraform", 
        "thefuck", 
        "timer", 
        "urltools", 
        "https://github.com/agkozak/zsh-z",
    ]
    extras = [
        "eval $(thefuck --alias f)",
    ]

    [[plugins.zsh.aliases]]
    name = "reload"
    cmd = "source ~/.zshrc"

    [[plugins.zsh.aliases]]
    name = "h"
    cmd = "history"

    [[plugins.zsh.aliases]]
    name = "hs"
    cmd = "history | grep -i"

    [[plugins.zsh.aliases]]
    name = "ff"
    cmd = "find . -type f -name"

    [[plugins.zsh.aliases]]
    name = "x"
    cmd = "xclip -sel clip"

    [[plugins.zsh.aliases]]
    name = "drun"
    cmd = "docker run -it --rm"

    [[plugins.zsh.aliases]]
    name = "kubectl"
    cmd = "kubecolor"

    [[plugins.zsh.aliases]]
    name = "k"
    cmd = "kubectl"

    [[plugins.zsh.aliases]]
    name = "kns"
    cmd = "kubens"

    [[plugins.zsh.aliases]]
    name = "kctx"
    cmd = "kubectx"

    [[plugins.zsh.aliases]]
    name = "ll"
    cmd = "ls -lh"

    [[plugins.zsh.aliases]]
    name = "lla"
    cmd = "ls -lAh"

    [[plugins.zsh.aliases]]
    name = "df"
    cmd = "df -h"

    [[plugins.zsh.aliases]]
    name = "free"
    cmd = "free -m"

    [[plugins.zsh.aliases]]
    name = "duh"
    cmd = "du -h -d 1"
