[options]
bind_ssh_folder = true
bind_home_folder = true
forward_x11 = true
docker_in_docker = true

[workspace]
hostname = "devops"
default_shell = "zsh"
tools = [ 
    "ansible", 
    "docker", 
    "docker-compose", 
    "dog", 
    "gcc", 
    "git", 
    "golang", 
    "helm", 
    "htop", 
    "knative-client", 
    "kubectl", 
    "kubectx", 
    "make", 
    "mysql-client", 
    "netcat", 
    "scw", 
    "terraform", 
    "thefuck", 
    "vim", 
    "xclip",
]

[[workspace.volumes]]
host = "/tmp/kitt"
bind = "/tmp"
mode = "rw"

[[workspace.envs]]
name = "DOCKER_BUILDKIT"
value = "1"

[[workspace.envs]]
name = "TIMER_FORMAT"
value = "[%d]"

[[workspace.envs]]
name = "TIMER_PRECISION"
value = "2"

[[workspace.envs]]
name = "MAGIC_ENTER_GIT_COMMAND"
value = "git status"

[[workspace.envs]]
name = "MAGIC_ENTER_OTHER_COMMAND"
value = "ls"

[plugins]

    [plugins.zsh]
    theme = "afowler"
    plugins = [ 
        "aliases", 
        "ansible", 
        "aws", 
        "colored-man-pages", 
        "copybuffer", 
        "docker", 
        "docker-compose", 
        "git", 
        "helm", 
        "kn", 
        "kubectl", 
        "kubectx", 
        "magic-enter", 
        "pip", 
        "python", 
        "terraform", 
        "thefuck", 
        "timer", 
        "urltools", 
        "https://github.com/agkozak/zsh-z",
    ]
    extras = [
        "eval $(thefuck --alias f)"
    ]

    [[plugins.zsh.alias]]
    name = "reload"
    cmd = "source ~/.zshrc"

    [[plugins.zsh.alias]]
    name = "h"
    cmd = "history"

    [[plugins.zsh.alias]]
    name = "hs"
    cmd = "history | grep -i"

    [[plugins.zsh.alias]]
    name = "ff"
    cmd = "find . -type f -name"

    [[plugins.zsh.alias]]
    name = "x"
    cmd = "xclip -sel clip"

    [[plugins.zsh.alias]]
    name = "drun"
    cmd = "docker run -it --rm"