# ----
# This is the default config file for Kitt.
# This file SHOULD NOT be edited.
# Run `kitt -f <custom_file> <name>` instead
# ----
# For a comprehensive version with comments
# and all availables options, see ../examples/default.conf
# ----

[options]
docker_in_docker = false    # Share docker socket
forward_x11 = false         # Configure x11 forward

[workspace]
image = "ubuntu:22.04"  # OCI System Image
tools = []              # Nix tools
user = "user"           # Username inside container
hostname = "kitt"       # Container hostname
default_shell = "bash"  # One of bash, zsh, sh, dash

[secrets]
[plugins]