FROM nixos/nix:2.11.1 as nixbuilder

RUN mkdir -p /output/store
RUN echo '#!/bin/sh' > /add \
    && echo 'nix-channel --update' >> /add \
    && echo 'echo -n $@ | xargs -d " " -I {} echo -n "nixpkgs.{} " | xargs nix-env -p /output/profile -iA' >> /add \
    && chmod +x /add

RUN /add {{ tools | join(' ') }}
RUN cp -va $(nix-store -qR /output/profile) /output/store


# PRE-BUILD STAGE
FROM alpine:3.15 as prebuild

ARG FIXUID_VERSION=0.5.1
ARG FIXUID_RELEASE=https://github.com/boxboat/fixuid/releases/download/v${FIXUID_VERSION}/fixuid-${FIXUID_VERSION}-linux-amd64.tar.gz

RUN wget -O - ${FIXUID_RELEASE} | tar -C / -xzf -

ARG ZSHID_VERSION=1.1.2
ARG ZSHID_RELEASE=https://github.com/deluan/zsh-in-docker/releases/download/v${ZSHID_VERSION}/zsh-in-docker.sh

RUN wget -O /zsh-in-docker ${FIXUID_RELEASE}


# RUNTIME STAGE
FROM {{ image }}

ARG USER={{ user }}
ARG SHELL={{ shell }}
ARG HOME=/home/${USER}

# CMD export $PATH
ENV USER=${USER}
{% for env in envs %}
{% for name, value in env.items() %}
ENV {{ name }}="{{ value }}"
{% endfor %}
{% endfor %}

RUN addgroup --gid 1000 ${USER} \
    && adduser --uid 1000 --ingroup ${USER} --home ${HOME} \
    --shell $(which ${SHELL} || which bash || which sh) \
    --disabled-password --gecos "" ${USER}

COPY --from=prebuild --chown=root:root /fixuid /bin/fixuid
RUN chmod 4755 /bin/fixuid \
    && mkdir -p /etc/fixuid \
    && echo "user: ${USER}" > /etc/fixuid/config.yml \
    && echo "group: ${USER}" >> /etc/fixuid/config.yml

{% for plugin in plugins %}
{{ plugin }}

{% endfor %}

# Last command to patch lack of sudo (enable passwordless `su root')
RUN chsh -s $(which ${SHELL} || which bash || which sh) ${USER} \
    && chsh -s $(which ${SHELL} || which bash || which sh) root \
    && echo 'source ~/.kittrc' >> ${HOME}/.bashrc \
    && echo 'source ~/.kittrc' >> /root/.bashrc \
    && chown ${USER}:${USER} ${HOME}/.kittrc \
    # && rm -rf /nix/store/*-nixpkgs || true \
    && passwd -d user \
    && passwd -d root

USER ${USER}:${USER}
WORKDIR ${HOME}

ENTRYPOINT [ "fixuid", "-q" ]