# This is a config file sample

[options]
bind_ssh_folder = true
network_host_mode = true

[workspace]
tools = []          # Catalog tools
hostname = "kitt"   # Container hostname
volumes = []        # Container bind volumes
envs = []           # Container exported ENV

# Plugins are optional additional
# features for container customisations.
# See plugins.py for further informations
[plugins]

    [plugins.zsh]
    theme = "afowler"
    plugins = []
    extras = []

    # [plugins.xforward]
    # x_server = "xorg"

    # [plugins.files]
    # files = []

    # [plugins.secrets]
    # files = []
