# This is a config file sample

[options]
bind_home_folder = false    # Bind $HOME with docker $HOME (read-write)
bind_ssh_folder = false     # Bind $HOME/.ssh (read-only)
docker_in_docker = false    # Share docker socket
forward_x11 = false         # Configure x11 forward

[workspace]
tools = []          # Catalog tools
hostname = "kitt"   # Container hostname
envs = []           # Remove if any (see bellow)
volumes = []        # Remove if any (see bellow)

# [[workspace.envs]]  # Container exported ENV (multiple)
# name = ""
# value = ""

# [[workspace.volumes]]   # Container bind volumes (multiple)
# host = ""   # Local directory
# bind = ""   # Bin inside container
# mode = ""   # Mode (default is 'rw')

# Plugins are optional additional
# features for container customisations.
# See plugins.py for further informations
[plugins]

    # ===== ZSH =====#

    # [plugins.zsh]
    # theme = "afowler"
    # plugins = []    # Plugins name or link
    # extras = []     # Extra line for .zshrc
    # alias = []      # Remove if any (see bellow)

    # # Add zsh alias (multiple)
    # [[plugins.zsh.alias]]
    # name = ''
    # cmd = ''

    # ===== TMUX =====#

    # [plugins.tmux]
    # config = []

    # ===== SCREEN =====#

    # [plugins.screen]
    # config = []

    # ===== FILES =====# // Not yet implemented

    # [plugins.files]
    # files = []

    # ===== SECRETS =====# // Not yet implemented

    # [plugins.secrets]
    # files = []
