# FROM ubuntu:20.04
FROM senges/catalog:latest

# Set command prefix as non interactive
ARG DEBIAN_FRONTEND=noninteractive

# Default starting workdir is root home
WORKDIR "/root"

# Default entrypoint is bash (can override)
ENTRYPOINT [ "/bin/bash" ]

# Environment variables
__envs__

# Install Catalog packages
__tools__

# Install plugins
__plugins__